
package org.openspcoop2.core.tracciamento.ws.client.traccia.all;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-02-16T16:08:57.977+01:00
 * Generated source version: 2.7.4
 */

@WebFault(name = "tracciamento-service-exception", targetNamespace = "http://www.openspcoop2.org/core/tracciamento/management")
public class TracciamentoServiceException_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoServiceException tracciamentoServiceException;

    public TracciamentoServiceException_Exception() {
        super();
    }
    
    public TracciamentoServiceException_Exception(String message) {
        super(message);
    }
    
    public TracciamentoServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TracciamentoServiceException_Exception(String message, org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoServiceException tracciamentoServiceException) {
        super(message);
        this.tracciamentoServiceException = tracciamentoServiceException;
    }

    public TracciamentoServiceException_Exception(String message, org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoServiceException tracciamentoServiceException, Throwable cause) {
        super(message, cause);
        this.tracciamentoServiceException = tracciamentoServiceException;
    }

    public org.openspcoop2.core.tracciamento.ws.client.traccia.all.TracciamentoServiceException getFaultInfo() {
        return this.tracciamentoServiceException;
    }
}
